services:
  mysql-db:
    container_name: mydb
    build:
      context: ./db
    image: rikka0823/mysql-db-01
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      my-bridge-001:
    volumes:
      - db-data:/var/lib/mysql
  java-app:
    container_name: myapp
    build:
      context: ./api
    image: rikka0823/java-app-01
    ports:
      - "8080:8080"
    command: sh -c "./wait-for-it.sh mydb:3306 -- java -jar app.jar"
    environment:
      - DB_HOST_IP=mydb
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      my-bridge-001:
    depends_on:
      - mysql-db

  angular-ui:
    container_name: myweb
    build:
      context: ./ui
    image: rikka0823/angular-ui-01
    ports:
      - "80:80"
    networks:
      - my-bridge-001
    depends_on:
      - java-app

networks:
  my-bridge-001:

volumes:
  db-data:

